ArcAudioTest: cast ByteBuffer for jdk8 compatibility
Cast ByteBuffer instances to Buffer before calling clear().
This is because the overridden of clear() for ByteBuffer is introduced
in jdk9, resulting in java.lang.NoSuchMethodError exceptions when
being compiled with jdk>=9 and executing on pi-arc (jdk8).

BUG=b:161678113
TEST=1. cros tryjob -g 2315474 eve-release-tryjob to build a test image
     2. cros flash ssh://${DUT_IP} xBuddy://eve-release-tryjob/${IMAGE}
     3. tast run ${DUT_IP} arc.AudioSanity.*

Change-Id: Icc9cb526772fc1cdbbe2fae5b6f6eab092b4ba68