Update patch set 3
Patch Set 3:

Failed builds:
  luci.chromeos.cq/cq-orchestrator JOB_FAILED https://cr-buildbucket.appspot.com/build/8854486121232388416
    Merge conflict detected! Please rebase and retry.
    
        error: patch failed: docs/test_dependencies.md:1
        Falling back to three-way merge...
        Applied patch to 'docs/test_dependencies.md' cleanly.
        error: patch failed: src/chromiumos/tast/cmd/local_test_runner/main.go:1
        Falling back to three-way merge...
        Applied patch to 'src/chromiumos/tast/cmd/local_test_runner/main.go' with conflicts.
        U src/chromiumos/tast/cmd/local_test_runner/main.go

Patch-set: 3
Tag: autogenerated:cq:full-run