Update patch set 6
Patch Set 6:

This CL has failed the run. Reason:

Tryjob [chromeos/cq/cq-orchestrator](https://cr-buildbucket.appspot.com/build/8799659257987863041) has failed with summary:

---
Merge conflict detected! Please rebase and retry.

    Falling back to direct application...
    Falling back to direct application...
    error: patch failed: src/chromiumos/tast/local/bundles/cros/wmp/full_screenshot.go:1
    error: src/chromiumos/tast/local/bundles/cros/wmp/full_screenshot.go: patch does not apply
    Applied patch to 'src/chromiumos/tast/local/chrome/uiauto/wmp/screenshot.go' with conflicts.

Patch-set: 6
Attention: {"person_ident":"Gerrit User 1509882 \u003c1509882@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"ps#6: Tryjobs failed"}