Update patch set 2
Patch Set 2:

Dry run: Failed builds:
  luci.chromeos.cq/cq-orchestrator JOB_FAILED https://cr-buildbucket.appspot.com/build/8882176018017182016
    Merge conflict detected! Please rebase and retry.
    
        error: patch failed: android/BUILD.gn:1
        Falling back to three-way merge...
        Applied patch to 'android/BUILD.gn' with conflicts.
        U android/BUILD.gn

Patch-set: 2
Tag: autogenerated:cq:dry-run