Update patch set 1
Patch Set 1: Verified-1

(build sheriff here) I believe this CL breaks build in CQ, example:

https://cros-goldeneye.corp.google.com/chromeos/healthmonitoring/buildDetails?buildbucketId=8934435274337465648

> tast-local-tests-cros-0.0.1-r189:  * Vetting "chromiumos/tast/local/..."
> tast-local-tests-cros-0.0.1-r189: # chromiumos/tast/local/bundles/cros/audio/device
> tast-local-tests-cros-0.0.1-r189: src/chromiumos/tast/local/bundles/cros/audio/device/device.go:40: Error call has possible formatting directive %v
<...>
> tast-local-tests-cros-0.0.1-r189: >>> Failed to emerge chromeos-base/tast-local-tests-cros-0.0.1-r189 for /build/arm-generic/, Log file:

Patch-set: 1
Reviewer: Gerrit User 1126309 <1126309@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Label: Verified=-1