Update patch set 3
Patch Set 3:

Failed builds:
  luci.chromeos.cq/cq-orchestrator JOB_FAILED https://cr-buildbucket.appspot.com/build/8854374464742714336
    Merge conflict detected! Please rebase and retry.
    
        error: patch failed: src/chromiumos/tast/local/bundles/cros/lacros/shelf_launch.go:1
        Falling back to three-way merge...
        Applied patch to 'src/chromiumos/tast/local/bundles/cros/lacros/shelf_launch.go' with conflicts.
        U src/chromiumos/tast/local/bundles/cros/lacros/shelf_launch.go

Patch-set: 3
Tag: autogenerated:cq:full-run