Update patch set 4
Patch Set 4:

Failed builds:
  luci.chromeos.cq/cq-orchestrator JOB_FAILED https://cr-buildbucket.appspot.com/build/8885077087454944480
    Merge conflict detected! Please rebase and retry.
    
        error: Failed to merge in the changes.
        hint: Use 'git am --show-current-patch' to see the failed patch
        CONFLICT (content): Merge conflict in src/chromiumos/tast/local/bundles/cros/camera/cca_ui_intent.go

Patch-set: 4
Tag: autogenerated:cq:full-run