Update patch set 1
Patch Set 1:

The following build(s) failed:

poppy-paladin: The UnitTest stage failed: Packages failed in /mnt/host/source/chromite/bin/cros_run_unit_tests: chromeos-base/mttools The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'endswith' in https://luci-milo.appspot.com/buildbot/chromeos/poppy-paladin/5607

beaglebone-paladin: The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'endswith' in https://luci-milo.appspot.com/buildbot/chromeos/beaglebone-paladin/17602

wolf-paladin: The UnitTest stage failed: Packages failed in /mnt/host/source/chromite/bin/cros_run_unit_tests: chromeos-base/mttools The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'endswith' in https://luci-milo.appspot.com/buildbot/chromeos/wolf-paladin/18580

betty-paladin: The UnitTest stage failed: Packages failed in /mnt/host/source/chromite/bin/cros_run_unit_tests: chromeos-base/mttools The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'endswith' in https://luci-milo.appspot.com/buildbot/chromeos/betty-paladin/3702

kevin-arcnext-paladin: The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'endswith' in https://luci-milo.appspot.com/buildbot/chromeos/kevin-arcnext-paladin/1201

caroline-paladin: The UnitTest stage failed: Packages failed in /mnt/host/source/chromite/bin/cros_run_unit_tests: chromeos-base/mttools The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'endswith' in https://luci-milo.appspot.com/buildbot/chromeos/caroline-paladin... (truncated)

kevin-paladin: The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'endswith' in https://luci-milo.appspot.com/buildbot/chromeos/kevin-paladin/5340

lakitu-gpu-paladin: The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'endswith' in https://luci-milo.appspot.com/buildbot/chromeos/lakitu-gpu-paladin/4281

betty-arcnext-paladin: The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'endswith' The UnitTest stage failed: Packages failed in /mnt/host/source/chromite/bin/cros_run_unit_tests: chromeos-base/mttools in https://luci-milo.appspot.com/buildbot/chromeos/betty-arcne... (truncated)

tidus-paladin: The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'endswith' The UnitTest stage failed: Packages failed in /mnt/host/source/chromite/bin/cros_run_unit_tests: chromeos-base/mttools in https://luci-milo.appspot.com/buildbot/chromeos/tidus-paladin/3704

monroe-paladin: The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'endswith' The UnitTest stage failed: Packages failed in /mnt/host/source/chromite/bin/cros_run_unit_tests: chromeos-base/mttools in https://luci-milo.appspot.com/buildbot/chromeos/monroe-paladin/174... (truncated)

winky-paladin: The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'endswith' The HWTest [bvt-inline] stage failed: ** HWTest failed (code 1) ** The UnitTest stage failed: Packages failed in /mnt/host/source/chromite/bin/cros_run_unit_tests: chromeos-base/mttools in ... (truncated)

veyron_mighty-paladin: The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'endswith' in https://luci-milo.appspot.com/buildbot/chromeos/veyron_mighty-paladin/9535

zoombini-paladin: The UnitTest stage failed: Packages failed in /mnt/host/source/chromite/bin/cros_run_unit_tests: chromeos-base/mttools The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'endswith' in https://luci-milo.appspot.com/buildbot/chromeos/zoombini-paladin... (truncated)

glados-paladin: The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'endswith' The UnitTest stage failed: Packages failed in /mnt/host/source/chromite/bin/cros_run_unit_tests: chromeos-base/mttools in https://luci-milo.appspot.com/buildbot/chromeos/glados-paladin/952... (truncated)

nyan_big-paladin: The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'endswith' in https://luci-milo.appspot.com/buildbot/chromeos/nyan_big-paladin/5876

betty-arc64-paladin: The UnitTest stage failed: Packages failed in /mnt/host/source/chromite/bin/cros_run_unit_tests: chromeos-base/mttools The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'endswith' in https://luci-milo.appspot.com/buildbot/chromeos/betty-arc64-p... (truncated)

cave-paladin: The UnitTest stage failed: Packages failed in /mnt/host/source/chromite/bin/cros_run_unit_tests: chromeos-base/mttools The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'endswith' in https://luci-milo.appspot.com/buildbot/chromeos/cave-paladin/4498

fizz-paladin: The UnitTest stage failed: Packages failed in /mnt/host/source/chromite/bin/cros_run_unit_tests: chromeos-base/mttools The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'endswith' in https://luci-milo.appspot.com/buildbot/chromeos/fizz-paladin/4859

oak-paladin: The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'endswith' in https://luci-milo.appspot.com/buildbot/chromeos/oak-paladin/11546

veyron_rialto-paladin: The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'endswith' in https://luci-milo.appspot.com/buildbot/chromeos/veyron_rialto-paladin/8396

scarlet-paladin: The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'endswith' in https://luci-milo.appspot.com/buildbot/chromeos/scarlet-paladin/4766

stout-paladin: The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'endswith' The UnitTest stage failed: Packages failed in /mnt/host/source/chromite/bin/cros_run_unit_tests: chromeos-base/mttools in https://luci-milo.appspot.com/buildbot/chromeos/stout-paladin/26590

nyan_kitty-paladin: The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'endswith' in https://luci-milo.appspot.com/buildbot/chromeos/nyan_kitty-paladin/5880

hana-paladin: The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'endswith' in https://luci-milo.appspot.com/buildbot/chromeos/hana-paladin/3826

gale-paladin: The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'endswith' in https://luci-milo.appspot.com/buildbot/chromeos/gale-paladin/6797

auron_yuna-paladin: The UnitTest stage failed: Packages failed in /mnt/host/source/chromite/bin/cros_run_unit_tests: chromeos-base/mttools The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'endswith' in https://luci-milo.appspot.com/buildbot/chromeos/auron_yuna-pal... (truncated)

daisy_skate-paladin: The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'endswith' in https://luci-milo.appspot.com/buildbot/chromeos/daisy_skate-paladin/14140

veyron_speedy-paladin: The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'endswith' in https://luci-milo.appspot.com/buildbot/chromeos/veyron_speedy-paladin/9534

nami-paladin: The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'endswith' The UnitTest stage failed: Packages failed in /mnt/host/source/chromite/bin/cros_run_unit_tests: chromeos-base/mttools in https://luci-milo.appspot.com/buildbot/chromeos/nami-paladin/2043

quawks-paladin: The UnitTest stage failed: Packages failed in /mnt/host/source/chromite/bin/cros_run_unit_tests: chromeos-base/mttools The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'endswith' in https://luci-milo.appspot.com/buildbot/chromeos/quawks-paladin/370... (truncated)

daisy-paladin: The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'endswith' in https://luci-milo.appspot.com/buildbot/chromeos/daisy-paladin/30252

rainier-paladin: The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'endswith' in https://luci-milo.appspot.com/buildbot/chromeos/rainier-paladin/1974

kip-paladin: The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'endswith' The UnitTest stage failed: Packages failed in /mnt/host/source/chromite/bin/cros_run_unit_tests: chromeos-base/mttools in https://luci-milo.appspot.com/buildbot/chromeos/kip-paladin/5870

leon-paladin: The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'endswith' The UnitTest stage failed: Packages failed in /mnt/host/source/chromite/bin/cros_run_unit_tests: chromeos-base/mttools in https://luci-milo.appspot.com/buildbot/chromeos/leon-paladin/18010

terra-paladin: The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'endswith' The UnitTest stage failed: Packages failed in /mnt/host/source/chromite/bin/cros_run_unit_tests: chromeos-base/mttools in https://luci-milo.appspot.com/buildbot/chromeos/terra-paladin/1535

chell-nowithdebug-paladin: The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'endswith' The UnitTest stage failed: Packages failed in /mnt/host/source/chromite/bin/cros_run_unit_tests: chromeos-base/mttools in https://luci-milo.appspot.com/buildbot/chromeos/chell-n... (truncated)

daisy_spring-paladin: The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'endswith' in https://luci-milo.appspot.com/buildbot/chromeos/daisy_spring-paladin/19525

samus-paladin: The UnitTest stage failed: Packages failed in /mnt/host/source/chromite/bin/cros_run_unit_tests: chromeos-base/mttools The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'endswith' in https://luci-milo.appspot.com/buildbot/chromeos/samus-paladin/18018

veyron_minnie-paladin: The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'endswith' in https://luci-milo.appspot.com/buildbot/chromeos/veyron_minnie-paladin/6807

moblab-generic-vm-paladin: The UnitTest stage failed: Packages failed in /mnt/host/source/chromite/bin/cros_run_unit_tests: chromeos-base/mttools in https://luci-milo.appspot.com/buildbot/chromiumos/moblab-generic-vm-paladin/2335

panther-paladin: The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'endswith' The UnitTest stage failed: Packages failed in /mnt/host/source/chromite/bin/cros_run_unit_tests: chromeos-base/mttools in https://luci-milo.appspot.com/buildbot/chromeos/panther-paladin/1... (truncated)

wizpig-paladin: The HWTest [bvt-inline] stage failed: ** HWTest failed (code 1) ** The UnitTest stage failed: Packages failed in /mnt/host/source/chromite/bin/cros_run_unit_tests: chromeos-base/mttools The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'endswith' in... (truncated)

peach_pit-paladin: The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'endswith' in https://luci-milo.appspot.com/buildbot/chromeos/peach_pit-paladin/19979

caroline-arcnext-paladin: The UnitTest stage failed: Packages failed in /mnt/host/source/chromite/bin/cros_run_unit_tests: chromeos-base/mttools The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'endswith' in https://luci-milo.appspot.com/buildbot/chromeos/caroline... (truncated)

veyron_tiger-paladin: The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'endswith' in https://luci-milo.appspot.com/buildbot/chromeos/veyron_tiger-paladin/3986

lakitu-paladin: The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'endswith' in https://luci-milo.appspot.com/buildbot/chromeos/lakitu-paladin/10698

veyron_jaq-paladin: The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'endswith' in https://luci-milo.appspot.com/buildbot/chromeos/veyron_jaq-paladin/4197

tricky-paladin: The UnitTest stage failed: Packages failed in /mnt/host/source/chromite/bin/cros_run_unit_tests: chromeos-base/mttools The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'endswith' in https://luci-milo.appspot.com/buildbot/chromeos/tricky-paladin/124... (truncated)

elm-paladin: The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'endswith' in https://luci-milo.appspot.com/buildbot/chromeos/elm-paladin/6989

link-paladin: The UnitTest stage failed: Packages failed in /mnt/host/source/chromite/bin/cros_run_unit_tests: chromeos-base/mttools The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'endswith' in https://luci-milo.appspot.com/buildbot/chromeos/link-paladin/32569

chell-paladin: The UnitTest stage failed: Packages failed in /mnt/host/source/chromite/bin/cros_run_unit_tests: chromeos-base/mttools The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'endswith' in https://luci-milo.appspot.com/buildbot/chromeos/chell-paladin/5460

guado_moblab-paladin: The UnitTest stage failed: Packages failed in /mnt/host/source/chromite/bin/cros_run_unit_tests: chromeos-base/autotest chromeos-base/mttools The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'endswith' in https://luci-milo.appspot.com/buildbo... (truncated)

amd64-generic-paladin: The UnitTest stage failed: Packages failed in /mnt/host/source/chromite/bin/cros_run_unit_tests: chromeos-base/mttools in https://luci-milo.appspot.com/buildbot/chromiumos/amd64-generic-paladin/33613

falco-paladin: The UnitTest stage failed: Packages failed in /mnt/host/source/chromite/bin/cros_run_unit_tests: chromeos-base/mttools The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'endswith' in https://luci-milo.appspot.com/buildbot/chromeos/falco-paladin/19426

octopus-paladin: The UnitTest stage failed: Packages failed in /mnt/host/source/chromite/bin/cros_run_unit_tests: chromeos-base/mttools The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'endswith' in https://luci-milo.appspot.com/buildbot/chromeos/octopus-paladin/1... (truncated)

bob-paladin: The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'endswith' The HWTest [bvt-inline] stage failed: ** HWTest failed (code 1) ** in https://luci-milo.appspot.com/buildbot/chromeos/bob-paladin/3827

veyron_jerry-paladin: The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'endswith' in https://luci-milo.appspot.com/buildbot/chromeos/veyron_jerry-paladin/4116

cyan-paladin: The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'endswith' The HWTest [bvt-arc] stage failed: ** HWTest failed (code 1) ** The UnitTest stage failed: Packages failed in /mnt/host/source/chromite/bin/cros_run_unit_tests: chromeos-base/mttools in http... (truncated)

grunt-paladin: The UnitTest stage failed: Packages failed in /mnt/host/source/chromite/bin/cros_run_unit_tests: chromeos-base/mttools The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'endswith' in https://luci-milo.appspot.com/buildbot/chromeos/grunt-paladin/2598

peppy-paladin: The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'endswith' The UnitTest stage failed: Packages failed in /mnt/host/source/chromite/bin/cros_run_unit_tests: chromeos-base/mttools in https://luci-milo.appspot.com/buildbot/chromeos/peppy-paladin/19396

sentry-paladin: The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'endswith' The UnitTest stage failed: Packages failed in /mnt/host/source/chromite/bin/cros_run_unit_tests: chromeos-base/mttools in https://luci-milo.appspot.com/buildbot/chromeos/sentry-paladin/382... (truncated)

edgar-paladin: The UnitTest stage failed: Packages failed in /mnt/host/source/chromite/bin/cros_run_unit_tests: chromeos-base/mttools The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'endswith' in https://luci-milo.appspot.com/buildbot/chromeos/edgar-paladin/3705

lakitu-st-paladin: The Archive stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'endswith' in https://luci-milo.appspot.com/buildbot/chromeos/lakitu-st-paladin/3822

Your change may have caused this failure. There are also other changes that may be at fault: 55 other changes. See the blamelist for more details.

Commit queue documentation: https://dev.chromium.org/developers/tree-sheriffs/sheriff-details-chromium-os/commit-queue-overview

Patch-set: 1