Update patch set 3
Patch Set 3:

Failed builds:
  luci.chromeos.cq/cq-orchestrator JOB_FAILED https://cr-buildbucket.appspot.com/build/8883101693371496112
    Merge conflict detected! Please rebase and retry.
    
        error: patch failed: src/chromiumos/tast/remote/firmware/config.go:1
        Falling back to three-way merge...
        Applied patch to 'src/chromiumos/tast/remote/firmware/config.go' with conflicts.
        U src/chromiumos/tast/remote/firmware/config.go

Patch-set: 3
Tag: autogenerated:cq:full-run