Update patch set 6
Patch Set 6:

Failed builds:
  luci.chromeos.cq/cq-orchestrator JOB_FAILED https://cr-buildbucket.appspot.com/build/8834949960804634929
    Merge conflict detected! Please rebase and retry.
    
        error: unrecognized input
  luci.chromeos.infra/Test Recipes Presubmit JOB_FAILED https://cr-buildbucket.appspot.com/build/8834949960804634065
    recipe infra failure: Infra Failure: Step('apply gerrit changes.gerrit-fetch-changes') (retcode: 1)

Patch-set: 6
Tag: autogenerated:cv