Update patch set 6
Patch Set 6:

Failed builds:
  luci.chromeos.cq/cq-orchestrator JOB_FAILED https://cr-buildbucket.appspot.com/build/8829727456310171409
    Merge conflict detected! Please rebase and retry.
    
        Applied patch to 'src/chromiumos/tast/common/cros/nearbyshare/constants.go' cleanly.
        error: src/chromiumos/tast/common/cros/nearbyshare/data/big_txt.zip.external: does not exist in index
        error: cannot read the current contents of 'src/chromiumos/tast/common/cros/nearbyshare/data/big_txt.zip.external'
        Falling back to direct application...
        error: src/chromiumos/tast/common/cros/nearbyshare/data/small_jpg.zip.external: does not exist in index
        error: cannot read the current contents of 'src/chromiumos/tast/common/cros/nearbyshare/data/small_jpg.zip.external'
        Falling back to direct application...
        error: src/chromiumos/tast/common/cros/nearbyshare/data/small_png.zip.external: does not exist in index
        error: cannot read the current contents of 'src/chromiumos/tast/common/cros/nearbyshare/data/small_png.zip.external'
        Falling back to direct application...
        Falling back to direct application...
        Applied patch to 'src/chromiumos/tast/local/chrome/nearbyshare/data/big_txt.zip.external' with conflicts.
        Falling back to direct application...
        Applied patch to 'src/chromiumos/tast/local/chrome/nearbyshare/data/small_jpg.zip.external' with conflicts.
        Falling back to direct application...
        Applied patch to 'src/chromiumos/tast/local/chrome/nearbyshare/data/small_png.zip.external' with conflicts.
        Applied patch to 'src/chromiumos/tast/remote/bundles/cros/nearbyshare/cros_to_cros_background_scanning.go' cleanly.
        Applied patch to 'src/chromiumos/tast/remote/bundles/cros/nearbyshare/cros_to_cros_high_vis.go' cleanly.
        Applied patch to 'src/chromiumos/tast/remote/bundles/cros/nearbyshare/cros_to_cros_in_contacts.go' cleanly.
        Falling back to direct application...
        Falling back to direct application...
        Falling back to direct application...
        Applied patch to 'src/chromiumos/tast/remote/bundles/cros/nearbyshare/smoke_multi_dut_ui.go' cleanly.
        error: src/chromiumos/tast/remote/cros/nearbyshare/data/big_txt.zip.external: does not exist in index
        error: cannot read the current contents of 'src/chromiumos/tast/remote/cros/nearbyshare/data/big_txt.zip.external'
        Falling back to direct application...
        error: src/chromiumos/tast/remote/cros/nearbyshare/data/small_jpg.zip.external: does not exist in index
        error: cannot read the current contents of 'src/chromiumos/tast/remote/cros/nearbyshare/data/small_jpg.zip.external'
        Falling back to direct application...
        error: src/chromiumos/tast/remote/cros/nearbyshare/data/small_png.zip.external: does not exist in index
        error: cannot read the current contents of 'src/chromiumos/tast/remote/cros/nearbyshare/data/small_png.zip.external'
        Falling back to direct application...
        Applied patch to 'src/chromiumos/tast/remote/cros/nearbyshare/fixture.go' cleanly.
        U src/chromiumos/tast/local/chrome/nearbyshare/data/big_txt.zip.external
        U src/chromiumos/tast/local/chrome/nearbyshare/data/small_jpg.zip.external
        U src/chromiumos/tast/local/chrome/nearbyshare/data/small_png.zip.external

Patch-set: 6
Tag: autogenerated:cq:full-run
Attention: {"person_ident":"Gerrit User 1390967 \u003c1390967@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"ps#6: CQ full run failed."}