Update patch set 1
Patch Set 1:

Failed builds:
  luci.chromeos.cq/cq-orchestrator JOB_FAILED https://cr-buildbucket.appspot.com/build/8876145761809424528
    Merge conflict detected! Please rebase and retry.
    
        error: patch failed: android/ArcKeyboardTest/AndroidManifest.xml:1
        Falling back to three-way merge...
        Applied patch to 'android/ArcKeyboardTest/AndroidManifest.xml' with conflicts.
        U android/ArcKeyboardTest/AndroidManifest.xml

Patch-set: 1
Tag: autogenerated:cq:full-run