kernel_iwlwifi_error: add to wifi_matfunc
crash.KernelIwlwifi was missing from https://crrev.com/c/2716844. It
should be both in bvt-tast-cq and wifi_matfunc, not just bvt-tast-cq

BUG=b:181060056
TEST=tast list $DUT '("group:wificell" && wificell_func)' | grep
KernelIwlwifiError
TEST=tast list $DUT '("group:mainline" && !informational &&
!"dep:chrome" && !"dep:plugin_vm" && !"name:crostini.*" &&
!"dep:android*")' | grep KernelIwlwifiError

Change-Id: I1f7fd0af1c0c8206cf4e8c5d59a225512d1f83f3
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/tast-tests/+/2716852
Commit-Queue: Nicolas Norvez <norvez@chromium.org>
Commit-Queue: Yen-lin Lai <yenlinlai@chromium.org>
Tested-by: Nicolas Norvez <norvez@chromium.org>
Auto-Submit: Nicolas Norvez <norvez@chromium.org>
Reviewed-by: Yen-lin Lai <yenlinlai@chromium.org>