Update patch set 2
Patch Set 2:

Failed builds:
  luci.chromeos.cq/cq-orchestrator JOB_FAILED https://cr-buildbucket.appspot.com/build/8872890618935018992
    Merge conflict detected! Please rebase and retry.
    
        error: patch failed: src/chromiumos/tast/local/bundles/cros/printer/print_usb.go:1
        Falling back to three-way merge...
        Applied patch to 'src/chromiumos/tast/local/bundles/cros/printer/print_usb.go' with conflicts.
        U src/chromiumos/tast/local/bundles/cros/printer/print_usb.go

Patch-set: 2
Tag: autogenerated:cq:full-run
Attention: {"person_ident":"Gerrit User 1304283 \u003c1304283@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"reviewer or cc replied"}