Update patch set 2
Patch Set 2:

Failed builds:
  luci.chromeos.cq/cq-orchestrator JOB_FAILED https://cr-buildbucket.appspot.com/build/8834676565570326161
    Merge conflict detected! Please rebase and retry.
    
        Applied patch to 'src/chromiumos/tast/local/bundles/cros/familylink/bed_time_limit.go' cleanly.
        Applied patch to 'src/chromiumos/tast/local/bundles/cros/lockscreen/keyboard_shortcut.go' cleanly.
        Applied patch to 'src/chromiumos/tast/local/bundles/cros/lockscreen/pin_unlock.go' cleanly.
        Applied patch to 'src/chromiumos/tast/local/bundles/cros/lockscreen/signout.go' cleanly.
        Applied patch to 'src/chromiumos/tast/local/bundles/cros/login/existing_user.go' cleanly.
        Applied patch to 'src/chromiumos/tast/local/bundles/cros/policy/allow_screen_lock.go' cleanly.
        Applied patch to 'src/chromiumos/tast/local/bundles/cros/policy/wallpaper_image.go' cleanly.
        Applied patch to 'src/chromiumos/tast/local/bundles/cros/quicksettings/lock_screen.go' with conflicts.
        Applied patch to 'src/chromiumos/tast/local/bundles/cros/u2fd/webauthn_using_pin.go' cleanly.
        Applied patch to 'src/chromiumos/tast/local/chrome/ui/quicksettings/quicksettings.go' cleanly.
        error: repository lacks the necessary blob to perform 3-way merge.
        Falling back to direct application...
        U src/chromiumos/tast/local/bundles/cros/quicksettings/lock_screen.go

Patch-set: 2
Tag: autogenerated:cv