Update patch set 4
Patch Set 4:

Failed builds:
  luci.chromeos.cq/cq-orchestrator JOB_FAILED https://cr-buildbucket.appspot.com/build/8885018308302513360
    Merge conflict detected! Please rebase and retry.
    
        error: Failed to merge in the changes.
        hint: Use 'git am --show-current-patch' to see the failed patch
        CONFLICT (content): Merge conflict in src/chromiumos/tast/remote/bundles/cros/firmware/check_boot_mode.go

Patch-set: 4
Tag: autogenerated:cq:full-run