Update patch set 4
Patch Set 4:

Failed builds:
  luci.chromeos.cq/cq-orchestrator JOB_FAILED https://cr-buildbucket.appspot.com/build/8862215714142718944
    Merge conflict detected! Please rebase and retry.
    
        error: src/chromiumos/tast/local/bundles/cros/inputs/virtual_keyboard_typing_browser.go: does not exist in index

Patch-set: 4
Tag: autogenerated:cq:full-run