Update patch set 2
Patch Set 2:

Failed builds:
  luci.chromeos.cq/cq-orchestrator JOB_FAILED https://cr-buildbucket.appspot.com/build/8840662233638329088
    Merge conflict detected! Please rebase and retry.
    
        error: patch failed: src/chromiumos/tast/local/bundles/cros/arc/resize_lock.go:1
        Falling back to three-way merge...
        Applied patch to 'src/chromiumos/tast/local/bundles/cros/arc/resize_lock.go' with conflicts.
        U src/chromiumos/tast/local/bundles/cros/arc/resize_lock.go

Patch-set: 2
Tag: autogenerated:cv