Update patch set 3
Patch Set 3:

Dry run: Failed builds:
  luci.chromeos.cq/cq-orchestrator JOB_FAILED https://cr-buildbucket.appspot.com/build/8837258266146600961
    Merge conflict detected! Please rebase and retry.
    
        error: RPC failed; curl 28 Operation too slow. Less than 1000 bytes/sec transferred the last 300 seconds
        fatal: error reading section header 'acknowledgments'
        [W git.go:289] Transient error string identified in STDERR: "error: RPC failed; curl 28 Operation too slow. Less than 1000 bytes/sec transferred the last 300 seconds\n"
        [W git.go:300] Retrying after 3s (rc=128): transient error string encountered

Patch-set: 3
Tag: autogenerated:cv