Update patch set 10
Patch Set 10:

Failed builds:
  luci.chromeos.cq/cq-orchestrator JOB_FAILED https://cr-buildbucket.appspot.com/build/8880985336641964448
    Merge conflict detected! Please rebase and retry.
    
        error: patch failed: src/chromiumos/tast/local/bundles/cros/network/wifi_service.go:1
        Falling back to three-way merge...
        Applied patch to 'src/chromiumos/tast/local/bundles/cros/network/wifi_service.go' cleanly.
        error: patch failed: src/chromiumos/tast/remote/wificell/hostapd/config.go:1
        Falling back to three-way merge...
        Applied patch to 'src/chromiumos/tast/remote/wificell/hostapd/config.go' cleanly.
        error: patch failed: src/chromiumos/tast/remote/wificell/hostapd/config_test.go:1
        Falling back to three-way merge...
        Applied patch to 'src/chromiumos/tast/remote/wificell/hostapd/config_test.go' cleanly.
        error: patch failed: src/chromiumos/tast/remote/wificell/test_fixture.go:1
        Falling back to three-way merge...
        Applied patch to 'src/chromiumos/tast/remote/wificell/test_fixture.go' with conflicts.
        U src/chromiumos/tast/remote/wificell/test_fixture.go

Patch-set: 10
Tag: autogenerated:cq:full-run