Update patch set 1
Patch Set 1:

This CL has failed the run. Reason:

Tryjob [chromeos/cq/cq-orchestrator](https://cr-buildbucket.appspot.com/build/8797987336412010145) has failed with summary:

---
Merge conflict detected! Please rebase and retry.

    error: src/chromiumos/tast/local/bundles/cros/feedback/choose_to_share_system_and_app_info_and_metrics_or_not.go: does not exist in index
    Applied patch to 'src/chromiumos/tast/local/bundles/cros/feedback/verify_system_info_and_app_and_metrics_checkbox_state.go' cleanly.
    Applied patch to 'src/chromiumos/tast/local/bundles/cros/feedback/view_system_info.go' cleanly.

Patch-set: 1
Attention: {"person_ident":"Gerrit User 1510407 \u003c1510407@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"ps#1: Tryjobs failed"}