Update patch set 2
Patch Set 2:

Failed builds:
  luci.chromeos.cq/cq-orchestrator JOB_FAILED https://cr-buildbucket.appspot.com/build/8869592508083935920
    Merge conflict detected! Please rebase and retry.
    
        error: patch failed: src/chromiumos/tast/local/crostini/ui/installer.go:1
        Falling back to three-way merge...
        Applied patch to 'src/chromiumos/tast/local/crostini/ui/installer.go' with conflicts.
        U src/chromiumos/tast/local/crostini/ui/installer.go

Patch-set: 2
Tag: autogenerated:cq:full-run
Attention: {"person_ident":"Gerrit User 1370239 \u003c1370239@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"Someone else replied on the change"}