Update patch set 2
Patch Set 2:

Failed builds:
  luci.chromeos.cq/cq-orchestrator JOB_FAILED https://cr-buildbucket.appspot.com/build/8839084077434133616
    Merge conflict detected! Please rebase and retry.
    
        Cloning into '.'...
        error: 14592 bytes of body are still expected
        fetch-pack: unexpected disconnect while reading sideband packet
        fatal: early EOF
        fatal: index-pack failed

Patch-set: 2
Tag: autogenerated:cv