Revert "tast-tests: mark crostini.Launcher tests informational"
This reverts commit c040e19ea4cb419c7ea2dd40753c325f610d13a5.

Reason for revert: Breaks unit tests:
https://ci.chromium.org/ui/p/chromeos/builders/postsubmit/amd64-generic-asan-postsubmit/1255/overview

tast-local-tests-cros-0.0.2-r8598: --- FAIL: TestLauncherParams (0.17s)
tast-local-tests-cros-0.0.2-r8598:     launcher_test.go:62: launcher.go: Params is stale; run the following command to update:
tast-local-tests-cros-0.0.2-r8598:         TAST_GENERATE_UPDATE=1 ~/trunk/src/platform/tast/tools/go.sh test -count=1 chromiumos/tast/local/bundles/cros/crostini

Original change's description:
> tast-tests: mark crostini.Launcher tests informational
>
> BUG=b:207689782
> TEST=none
>
> Change-Id: I1acdd1a3a9e5a271cb97d74a90bfcd54e63f9814
> Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/tast-tests/+/3317316
> Reviewed-by: Joel Hockey <joelhockey@chromium.org>
> Reviewed-by: Yu-Ping Wu <yupingso@chromium.org>
> Tested-by: Joel Hockey <joelhockey@chromium.org>
> Owners-Override: Joel Hockey <joelhockey@chromium.org>
> Auto-Submit: Joel Hockey <joelhockey@chromium.org>
> Commit-Queue: Yu-Ping Wu <yupingso@chromium.org>

Bug: b:207689782
Change-Id: Id9c71b2a4d4c1f9bf1db9574595b7eb6e8ace5f2