Revert "sched.CoreSchedTag: Add vulnerability dependency"
This reverts commit 9f116ccdc4b30ec365c45e1771a31f9f8896e8af.

To work around:
core_sched_tag.go:39:55: undefined: hwdep.CPUNeedsCoreScheduling

Change-Id: Ibf6542389fba79b89d997269ee1cf9ba65e76530