Update patch set 4
Patch Set 4:

Failed builds:
  luci.chromeos.cq/cq-orchestrator JOB_FAILED https://cr-buildbucket.appspot.com/build/8853714868909113344
    Merge conflict detected! Please rebase and retry.
    
        error: patch failed: src/chromiumos/tast/local/bundles/cros/network/wifi_check_intel_sar_table.go:1
        Falling back to three-way merge...
        Applied patch to 'src/chromiumos/tast/local/bundles/cros/network/wifi_check_intel_sar_table.go' cleanly.
        error: patch failed: src/chromiumos/tast/remote/bundles/cros/wifi/channel_hop.go:1
        Falling back to three-way merge...
        Applied patch to 'src/chromiumos/tast/remote/bundles/cros/wifi/channel_hop.go' with conflicts.
        U src/chromiumos/tast/remote/bundles/cros/wifi/channel_hop.go

Patch-set: 4
Tag: autogenerated:cq:full-run