Update patch set 3
Patch Set 3: Verified-1 -Commit-Queue

It seems this commit breaks CQ. The test itself runs fine, but a linter fails for this test.

> tast-local-tests-cros-0.0.1-r2587: --- FAIL: TestTimeout (0.00s)
> tast-local-tests-cros-0.0.1-r2587:     testcheck.go:48: arc.Appfuse: timeout is too short (0s < 4m30s)
> tast-local-tests-cros-0.0.1-r2587: FAIL

https://logs.chromium.org/logs/chromeos/buildbucket/cr-buildbucket.appspot.com/8880970800094161328/+/steps/run_ebuild_tests/0/steps/call_chromite.api.TestService_BuildTargetUnitTest/0/steps/call_build_API_script/0/stdout

Patch-set: 3
Reviewer: Gerrit User 1411497 <1411497@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Label: Commit-Queue=0
Label: Verified=-1