Update patch set 3
Patch Set 3:

Dry run: Failed builds:
  luci.chromeos.cq/cq-orchestrator JOB_FAILED https://cr-buildbucket.appspot.com/build/8830520912643748161
    Merge conflict detected! Please rebase and retry.
    
        Falling back to direct application...
        Applied patch to 'src/chromiumos/tast/local/bundles/cros/platform/data/perfetto/perfetto_tbm_traced_probes.pbtxt' with conflicts.
        Falling back to direct application...
        Applied patch to 'src/chromiumos/tast/local/bundles/cros/platform/data/trace_processor_shell-amd64.external' with conflicts.
        Falling back to direct application...
        Applied patch to 'src/chromiumos/tast/local/bundles/cros/platform/data/trace_processor_shell-arm.external' with conflicts.
        Falling back to direct application...
        Applied patch to 'src/chromiumos/tast/local/bundles/cros/platform/data/trace_processor_shell-arm64.external' with conflicts.
        Applied patch to 'src/chromiumos/tast/local/bundles/cros/platform/local_perfetto_tbm_traced_probes.go' cleanly.
        Applied patch to 'src/chromiumos/tast/local/bundles/cros/platform/perfetto_chrome_consumer.go' cleanly.
        Applied patch to 'src/chromiumos/tast/local/bundles/cros/platform/perfetto_chrome_producer.go' cleanly.
        Applied patch to 'src/chromiumos/tast/local/bundles/cros/platform/perfetto_system_tracing.go' cleanly.
        error: repository lacks the necessary blob to perform 3-way merge.
        Falling back to direct application...
        0001-tracing-Transfer-tracing-data-files-to-local-tracing.patch:790: new blank line at EOF.
        +
        error: src/chromiumos/tast/local/tracing/data/perfetto_tbm_traced_probes.pbtxt: does not exist in index
        error: cannot read the current contents of 'src/chromiumos/tast/local/tracing/data/perfetto_tbm_traced_probes.pbtxt'
        Falling back to direct application...
        0001-tracing-Transfer-tracing-data-files-to-local-tracing.patch:790: new blank line at EOF.
        +
        error: src/chromiumos/tast/local/tracing/data/trace_processor_shell-amd64.external: does not exist in index
        error: cannot read the current contents of 'src/chromiumos/tast/local/tracing/data/trace_processor_shell-amd64.external'
        Falling back to direct application...
        error: src/chromiumos/tast/local/tracing/data/trace_processor_shell-arm.external: does not exist in index
        error: cannot read the current contents of 'src/chromiumos/tast/local/tracing/data/trace_processor_shell-arm.external'
        Falling back to direct application...
        error: src/chromiumos/tast/local/tracing/data/trace_processor_shell-arm64.external: does not exist in index
        error: cannot read the current contents of 'src/chromiumos/tast/local/tracing/data/trace_processor_shell-arm64.external'
        Falling back to direct application...
        error: repository lacks the necessary blob to perform 3-way merge.
        Falling back to direct application...
        U src/chromiumos/tast/local/bundles/cros/platform/data/perfetto/perfetto_tbm_traced_probes.pbtxt
        U src/chromiumos/tast/local/bundles/cros/platform/data/trace_processor_shell-amd64.external
        U src/chromiumos/tast/local/bundles/cros/platform/data/trace_processor_shell-arm.external
        U src/chromiumos/tast/local/bundles/cros/platform/data/trace_processor_shell-arm64.external
        warning: 2 lines add whitespace errors.

Patch-set: 3
Tag: autogenerated:cq:dry-run
Attention: {"person_ident":"Gerrit User 1349355 \u003c1349355@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"ps#3: CQ dry run failed."}