Update patch set 4
Patch Set 4:

Failed builds:
  luci.chromeos.cq/cq-orchestrator JOB_FAILED https://cr-buildbucket.appspot.com/build/8882033310585374672
    Merge conflict detected! Please rebase and retry.
    
        error: patch failed: src/chromiumos/tast/local/bundles/cros/arc/app_crash.go:1
        Falling back to three-way merge...
        Applied patch to 'src/chromiumos/tast/local/bundles/cros/arc/app_crash.go' with conflicts.
        error: src/chromiumos/tast/local/bundles/cros/arc/data/ArcAppCrashTest.apk.external: does not exist in index

Patch-set: 4
Tag: autogenerated:cq:full-run