Update patch set 2
Patch Set 2:

Failed builds:
  luci.chromeos.cq/cq-orchestrator JOB_FAILED https://cr-buildbucket.appspot.com/build/8834353998511063633
    Merge conflict detected! Please rebase and retry.
    
        Applied patch to 'src/chromiumos/tast/local/bundles/cros/familylink/bed_time_limit.go' cleanly.
        Applied patch to 'src/chromiumos/tast/local/bundles/cros/lockscreen/keyboard_shortcut.go' cleanly.
        Applied patch to 'src/chromiumos/tast/local/bundles/cros/lockscreen/pin_unlock.go' cleanly.
        Applied patch to 'src/chromiumos/tast/local/bundles/cros/lockscreen/signout.go' cleanly.
        Applied patch to 'src/chromiumos/tast/local/bundles/cros/login/existing_user.go' cleanly.
        Applied patch to 'src/chromiumos/tast/local/bundles/cros/policy/allow_screen_lock.go' cleanly.
        Applied patch to 'src/chromiumos/tast/local/bundles/cros/policy/wallpaper_image.go' cleanly.
        Applied patch to 'src/chromiumos/tast/local/bundles/cros/quicksettings/lock_screen.go' with conflicts.
        Applied patch to 'src/chromiumos/tast/local/bundles/cros/u2fd/webauthn_using_pin.go' cleanly.
        Applied patch to 'src/chromiumos/tast/local/chrome/ui/quicksettings/quicksettings.go' cleanly.
        error: repository lacks the necessary blob to perform 3-way merge.
        error: src/chromiumos/tast/local/chrome/ui/lockscreen/lockscreen.go: patch does not apply

Patch-set: 2
Tag: autogenerated:cv
Attention: {"person_ident":"Gerrit User 1519363 \u003c1519363@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"CV stopped processing the Run"}