Update patch set 2
Patch Set 2:

Dry run: Failed builds:
  luci.chromeos.cq/cq-orchestrator JOB_FAILED https://cr-buildbucket.appspot.com/build/8852477766263352656
    Merge conflict detected! Please rebase and retry.
    
        error: patch failed: src/chromiumos/tast/cmd/local_test_runner/main.go:1
        Falling back to three-way merge...
        Applied patch to 'src/chromiumos/tast/cmd/local_test_runner/main.go' with conflicts.
        U src/chromiumos/tast/cmd/local_test_runner/main.go

Patch-set: 2
Tag: autogenerated:cq:dry-run