Update patch set 11
Patch Set 11:

unrelated to those failures, i might've given bad advice earlier when i suggested removing the timeout. at least locally, this looks like it's making chromiumos/tast/local/bundles/cros/arc's TestTimeout test fail when i use "fast_build.sh -T" to run all unit tests:

--- FAIL: TestTimeout (0.00s)
        timeout_test.go:33: arc.SettingsBridge: timeout is too short (0s < 3m30s)
FAIL
FAIL    chromiumos/tast/local/bundles/cros/arc  0.125s

i'm surprised that this doesn't seem to be causing failures on builders. are we not running this unit test for some reason?

Patch-set: 11