video.*Perf*: Ignore failures while writing to intel_pstate/no_turbo.
This CL makes changes to allow ignoring failures while disabling CPU frequency
scaling mechanisms for specfied paths. On some platforms we don't have the right
permissions to disable frequency scaling, resulting in:
Error: Failed to set up benchmark mode: failed to disable CPU frequency scaling:
write /sys/devices/system/cpu/intel_pstate/no_turbo: operation not permitted

TEST=camera.DecodeAccelJPEGPerf on eve

BUG=chromium:938729

Change-Id: I372fee7837e23dcdec1ac2e86d4f4b490fc548d9