Update patch set 5
Patch Set 5:

Avery, it looks like the builder is failing due to build of tast binaries.

tast-local-tests-cros-0.0.1-r2521: --- FAIL: TestTimeout (0.00s)
tast-local-tests-cros-0.0.1-r2521:     testcheck.go:48: arc.SplitView.clamshell_mode: timeout is too short (0s < 4m30s)
tast-local-tests-cros-0.0.1-r2521: FAIL
tast-local-tests-cros-0.0.1-r2521: FAIL	chromiumos/tast/local/bundles/cros/arc	0.100s

It would reproduce on your environment through fast_check.sh -T (https://chromium.googlesource.com/chromiumos/platform/tast/+/refs/heads/master/docs/modifying_tast.md#fast_build_sh https://chromium.googlesource.com/chromiumos/platform/tast/+/refs/heads/master/docs/test_validation.md#unit-tests).

The timeout is enforced as https://chromium.googlesource.com/chromiumos/platform/tast-tests.git/+/refs/heads/master/src/chromiumos/tast/local/bundles/cros/arc/registration_test.go#39; you will have to set the Timeout, otherwise CQ won't pass.

Patch-set: 5
Reviewer: Gerrit User 1000479 <1000479@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>