crash.KernelIwlwifiError: fix timeout usage
crash.WaitForCrashFiles() enforces a default timeout of 15 seconds,
which supersedes our 60-second timeout. Tastboard shows that this
occasionally takes just a hair longer than 15 seconds (possibly because
iwlwifi is doing some complex restart/dump logic along the way) but
the test is declaring that a failure.

Let's make the 60-second timeout *really* work.

BUG=none
TEST=run it

Change-Id: Id7cbeaa94925dae9f3982d90b614e335dc75bc89
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/tast-tests/+/2548201
Tested-by: Brian Norris <briannorris@chromium.org>
Reviewed-by: Arowa Suliman <arowa@chromium.org>
Reviewed-by: Miriam Zimmerman <mutexlox@chromium.org>
Reviewed-by: Ricardo Quesada <ricardoq@chromium.org>
Commit-Queue: Brian Norris <briannorris@chromium.org>