Update patch set 1
Patch Set 1:

Failed builds:
  luci.chromeos.cq/cq-orchestrator JOB_FAILED https://cr-buildbucket.appspot.com/build/8849383809042994992
    Merge conflict detected! Please rebase and retry.
    
        error: patch failed: src/chromiumos/tast/local/bundles/cros/arc/optin.go:1
        Falling back to three-way merge...
        Applied patch to 'src/chromiumos/tast/local/bundles/cros/arc/optin.go' with conflicts.
        U src/chromiumos/tast/local/bundles/cros/arc/optin.go

Patch-set: 1
Tag: autogenerated:cq:full-run