Update patch set 5
Patch Set 5:

Dry run: Failed builds:
  luci.chromeos.cq/cq-orchestrator JOB_FAILED https://cr-buildbucket.appspot.com/build/8881686875029021776
    Merge conflict detected! Please rebase and retry.
    
        error: patch failed: src/chromiumos/tast/local/bundles/cros/wilco/wilco_service.go:1
        Falling back to three-way merge...
        Applied patch to 'src/chromiumos/tast/local/bundles/cros/wilco/wilco_service.go' with conflicts.
        error: patch failed: src/chromiumos/tast/services/cros/wilco/wilco_service.pb.go:1
        Falling back to three-way merge...
        Applied patch to 'src/chromiumos/tast/services/cros/wilco/wilco_service.pb.go' cleanly.
        error: patch failed: src/chromiumos/tast/services/cros/wilco/wilco_service.proto:1
        Falling back to three-way merge...
        Applied patch to 'src/chromiumos/tast/services/cros/wilco/wilco_service.proto' cleanly.
        U src/chromiumos/tast/local/bundles/cros/wilco/wilco_service.go

Patch-set: 5
Tag: autogenerated:cq:dry-run