Revert "tast-tests: Update recovery factor"
This reverts commit 306fa253edd6d3674f1a9e7a55046176472c6466.

Reason for revert: Fails to build with 
```
tast-remote-tests-cros-0.0.2-r12362: # chromiumos/tast/local/bundles/cros/cryptohome
tast-remote-tests-cros-0.0.2-r12362: src/chromiumos/tast/local/bundles/cros/cryptohome/update_recovery.go:82:78: not enough arguments in call to client.StartAuthSession
tast-remote-tests-cros-0.0.2-r12362: 	have (context.Context, string, bool)
tast-remote-tests-cros-0.0.2-r12362: 	want (context.Context, string, bool, user_data_auth_proto.AuthIntent)
tast-remote-tests-cros-0.0.2-r12362: src/chromiumos/tast/local/bundles/cros/cryptohome/update_recovery.go:117:63: not enough arguments in call to client.StartAuthSession
tast-remote-tests-cros-0.0.2-r12362: 	have (context.Context, string, bool)
tast-remote-tests-cros-0.0.2-r12362: 	want (context.Context, string, bool, user_data_auth_proto.AuthIntent)
```

Original change's description:
> tast-tests: Update recovery factor
>
> Update recovery factor and check that authentication is successful.
>
> BUG=b:240721996
> TEST=tast run <ip> cryptohome.UpdateRecovery
>
> Change-Id: Ic0300a2de087f08e620579e1000335713b4dc700
> Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/tast-tests/+/3871027
> Reviewed-by: Maksim Ivanov <emaxx@chromium.org>
> Reviewed-by: David Stevens <stevensd@chromium.org>
> Commit-Queue: Anastasiia N <anastasiian@chromium.org>
> Tested-by: Anastasiia N <anastasiian@chromium.org>

Bug: b:240721996
Change-Id: I0185f62f942f2d1272cbd4da090c2de1e18e6ee4
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/tast-tests/+/3885475
Auto-Submit: Jeremy Bettis <jbettis@chromium.org>
Commit-Queue: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Commit-Queue: Jeremy Bettis <jbettis@chromium.org>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Tested-by: Jeremy Bettis <jbettis@chromium.org>