Update patch set 3
Patch Set 3:

Failed builds:
  luci.chromeos.cq/cq-orchestrator JOB_FAILED https://cr-buildbucket.appspot.com/build/8860103237188205120
    Merge conflict detected! Please rebase and retry.
    
        error: chromeos-base/chromeos-bsp-atlas-private/chromeos-bsp-atlas-private-0.0.1-r15.ebuild: does not exist in index
        error: patch failed: chromeos-base/chromeos-bsp-atlas-private/chromeos-bsp-atlas-private-0.0.1.ebuild:1
        Falling back to three-way merge...
        Applied patch to 'chromeos-base/chromeos-bsp-atlas-private/chromeos-bsp-atlas-private-0.0.1.ebuild' cleanly.

Patch-set: 3
Tag: autogenerated:cq:full-run