Update patch set 4
Patch Set 4:

Failed builds:
  luci.chromeos.cq/cq-orchestrator JOB_FAILED https://cr-buildbucket.appspot.com/build/8843764563063917872
    Merge conflict detected! Please rebase and retry.
    
        error: patch failed: src/chromiumos/tast/local/bundles/cros/arc/pip.go:1
        Falling back to three-way merge...
        Applied patch to 'src/chromiumos/tast/local/bundles/cros/arc/pip.go' with conflicts.
        U src/chromiumos/tast/local/bundles/cros/arc/pip.go

Patch-set: 4
Tag: autogenerated:cq:full-run