video.*Perf*: Ignore failures while disabling CPU frequency scaling.
This CL makes changes to ignore failures while disabling CPU frequency scaling
mechanisms. On some platforms we don't have the right permissions to disabling
frequency scaling, resulting in:
Error: Failed to set up benchmark mode: failed to disable CPU frequency scaling:
write /sys/devices/system/cpu/intel_pstate/no_turbo: operation not permitted

We're still interested in the test results in this case, even if the results
might be slightly less stable.

TEST=camera.DecodeAccelJPEGPerf on eve

BUG=chromium:938729

Change-Id: I372fee7837e23dcdec1ac2e86d4f4b490fc548d9