Update patch set 6
Patch Set 6:

Failed builds:
  luci.chromeos.cq/cq-orchestrator JOB_FAILED https://cr-buildbucket.appspot.com/build/8878055649210145984
    Merge conflict detected! Please rebase and retry.
    
        error: patch failed: src/chromiumos/tast/local/bundles/cros/hwsec/account_disk_usage.go:1
        Falling back to three-way merge...
        Applied patch to 'src/chromiumos/tast/local/bundles/cros/hwsec/account_disk_usage.go' with conflicts.
        error: patch failed: src/chromiumos/tast/local/bundles/cros/hwsec/util/constants.go:1
        Falling back to three-way merge...
        Applied patch to 'src/chromiumos/tast/local/bundles/cros/hwsec/util/constants.go' cleanly.
        U src/chromiumos/tast/local/bundles/cros/hwsec/account_disk_usage.go

Patch-set: 6
Tag: autogenerated:cq:full-run