Update patch set 7
Patch Set 7:

Failed builds:
  luci.chromeos.cq/cq-orchestrator JOB_FAILED https://cr-buildbucket.appspot.com/build/8863333855399879216
    Merge conflict detected! Please rebase and retry.
    
        error: patch failed: src/chromiumos/tast/local/bundles/cros/arc/wm_resizable_tablet.go:1
        Falling back to three-way merge...
        Applied patch to 'src/chromiumos/tast/local/bundles/cros/arc/wm_resizable_tablet.go' with conflicts.
        U src/chromiumos/tast/local/bundles/cros/arc/wm_resizable_tablet.go

Patch-set: 7
Tag: autogenerated:cq:full-run