Update patch set 3
Patch Set 3:

Dan: you may want to wait on this review because the presubmit hook is not fully installed:

           * Hook script "tools/run_lint.sh -commit=${PRESUBMIT_COMMIT}" failed with code 1:
              ../tast/src/chromiumos/cmd/tast-lint/check/golint.go:11:2: cannot find package "golang.org/x/lint" in any of:
              	/usr/lib/google-golang/src/golang.org/x/lint (from $GOROOT)
              	/usr/local/google/home/semenzato/chromiumos/src/platform/tast/src/golang.org/x/lint (from $GOPATH)
              	/usr/local/google/home/semenzato/chromiumos/chroot/usr/lib/gopath/src/golang.org/x/lint
              *** Failed to build tast-lint. Please run update_chroot.


Unfortunately running update_chroot is broken too:

update_engine-0.0.3-r3278: /usr/lib/gcc/x86_64-pc-linux-gnu/4.9.x/../../../../lib64/libbspatch.so: undefined reference to `BrotliDecoderErrorString'

etc. etc.

Patch-set: 3
Reviewer: Gerrit User 1000042 <1000042@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Reviewer: Gerrit User 1000153 <1000153@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Reviewer: Gerrit User 1000028 <1000028@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>