Revert "arcappcompat: Create GaiaLoginPoolVars for handling testaccountpool"
This reverts commit 74f0e110983e59ee256dabe196980823339d7eda.

Reason for revert: Possibly collided with https://crrev.com/c/3282486 and broke CQ.

E.g. http://go/bbid/8829915238398946449
 "tast-remote-tests-cros-0.0.2-r8508: src/chromiumos/tast/local/bundles/cros/arcappgameperf/pre/pre.go:17:47: not enough arguments in call to arc.NewPrecondition"

Original change's description:
> arcappcompat: Create GaiaLoginPoolVars for handling testaccountpool
>
> It is observed that arcappcompat tests are failing in install
>  with Authentication error due to Playstore rate limit issue.
> Currently arcappcompat tests are using a single test account
> for most of the apps. Adding TestAccountPool for arcappcompat
> tests will fix the play store rate limit issue as the test
> could use any test account from the testaccount pool.Also
> in "pre" file created a struct GaiaLoginPoolVars for handling
> Testaccountpool so that any test can use their own pool credentials.
>
> BUG=b:197558039
> TEST=tast run <eve> arcappcompat.ABCKids.clamshell_mode
> tast run <eve> arcappcompat.ABCKids.tablet_mode
> tast run <helios> arcappcompat.ABCKids.vm_clamshell_mode
> tast run <helios> arcappcompat.ABCKids.vm_tablet_mode
>
> Cq-Depend: chrome-internal:4234621
> Change-Id: I601090f58dc145148d6ad1f6d42f228a3473362a
> Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/tast-tests/+/3290118
> Tested-by: Meenakshi Thiyagarajan <mthiyagarajan@google.com>
> Commit-Queue: Meenakshi Thiyagarajan <mthiyagarajan@google.com>
> Reviewed-by: Yury Khmel <khmel@chromium.org>
> Reviewed-by: Renuga Nanjappan <rnanjappan@chromium.org>
> Reviewed-by: David Welling <davidwelling@google.com>

Bug: b:197558039
Change-Id: If204b19504b9b634a56deb30adcc65cb1afa1a62
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/tast-tests/+/3295105
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Commit-Queue: Trent Apted <tapted@chromium.org>
Tested-by: Trent Apted <tapted@chromium.org>
Owners-Override: Trent Apted <tapted@chromium.org>