Update patch set 1
Patch Set 1:

Dry run: Failed builds:
  luci.chromeos.cq/cq-orchestrator JOB_FAILED https://cr-buildbucket.appspot.com/build/8875932840106151824
    Merge conflict detected! Please rebase and retry.
    
        error: patch failed: src/chromiumos/tast/local/bundles/cros/arcappcompat/adobe_acrobat_reader.go:1
        Falling back to three-way merge...
        Applied patch to 'src/chromiumos/tast/local/bundles/cros/arcappcompat/adobe_acrobat_reader.go' with conflicts.
        error: patch failed: src/chromiumos/tast/local/bundles/cros/arcappcompat/adobe_illustrator_draw.go:1
        Falling back to three-way merge...
        Applied patch to 'src/chromiumos/tast/local/bundles/cros/arcappcompat/adobe_illustrator_draw.go' with conflicts.
        error: patch failed: src/chromiumos/tast/local/bundles/cros/arcappcompat/amazon_prime_video.go:1
        Falling back to three-way merge...
        Applied patch to 'src/chromiumos/tast/local/bundles/cros/arcappcompat/amazon_prime_video.go' with conflicts.
        error: patch failed: src/chromiumos/tast/local/bundles/cros/arcappcompat/asphalt.go:1
        Falling back to three-way merge...
        Applied patch to 'src/chromiumos/tast/local/bundles/cros/arcappcompat/asphalt.go' with conflicts.
        error: patch failed: src/chromiumos/tast/local/bundles/cros/arcappcompat/concepts.go:1
        Falling back to three-way merge...
        Applied patch to 'src/chromiumos/tast/local/bundles/cros/arcappcompat/concepts.go' with conflicts.
        error: patch failed: src/chromiumos/tast/local/bundles/cros/arcappcompat/facebook.go:1
        Falling back to three-way merge...
        Applied patch to 'src/chromiumos/tast/local/bundles/cros/arcappcompat/facebook.go' with conflicts.
        error: patch failed: src/chromiumos/tast/local/bundles/cros/arcappcompat/gmail.go:1
        Falling back to three-way merge...
        Applied patch to 'src/chromiumos/tast/local/bundles/cros/arcappcompat/gmail.go' with conflicts.
        error: patch failed: src/chromiumos/tast/local/bundles/cros/arcappcompat/google_calendar.go:1
        Falling back to three-way merge...
        Applied patch to 'src/chromiumos/tast/local/bundles/cros/arcappcompat/google_calendar.go' with conflicts.
        error: patch failed: src/chromiumos/tast/local/bundles/cros/arcappcompat/google_duo.go:1
        Falling back to three-way merge...
        Applied patch to 'src/chromiumos/tast/local/bundles/cros/arcappcompat/google_duo.go' with conflicts.
        error: patch failed: src/chromiumos/tast/local/bundles/cros/arcappcompat/google_photos.go:1
        Falling back to three-way merge...
        Applied patch to 'src/chromiumos/tast/local/bundles/cros/arcappcompat/google_photos.go' with conflicts.
        error: patch failed: src/chromiumos/tast/local/bundles/cros/arcappcompat/hbomax.go:1
        Falling back to three-way merge...
        Applied patch to 'src/chromiumos/tast/local/bundles/cros/arcappcompat/hbomax.go' with conflicts.
        error: patch failed: src/chromiumos/tast/local/bundles/cros/arcappcompat/hearthstone.go:1
        Falling back to three-way merge...
        Applied patch to 'src/chromiumos/tast/local/bundles/cros/arcappcompat/hearthstone.go' with conflicts.
        error: patch failed: src/chromiumos/tast/local/bundles/cros/arcappcompat/hulu.go:1
        Falling back to three-way merge...
        Applied patch to 'src/chromiumos/tast/local/bundles/cros/arcappcompat/hulu.go' with conflicts.
        error: patch failed: src/chromiumos/tast/local/bundles/cros/arcappcompat/messenger.go:1
        Falling back to three-way merge...
        Applied patch to 'src/chromiumos/tast/local/bundles/cros/arcappcompat/messenger.go' with conflicts.
        error: patch failed: src/chromiumos/tast/local/bundles/cros/arcappcompat/microsoft_word.go:1
        Falling back to three-way merge...
        Applied patch to 'src/chromiumos/tast/local/bundles/cros/arcappcompat/microsoft_word.go' with conflicts.
        error: patch failed: src/chromiumos/tast/local/bundles/cros/arcappcompat/netflix.go:1
        Falling back to three-way merge...
        Applied patch to 'src/chromiumos/tast/local/bundles/cros/arcappcompat/netflix.go' with conflicts.
        error: patch failed: src/chromiumos/tast/local/bundles/cros/arcappcompat/pinterest.go:1
        Falling back to three-wa...

Patch-set: 1
Tag: autogenerated:cq:dry-run