Revert "Refactor graphics.VTSwitch to use perceptualdiff"
This reverts commit e86d5216f13fd4bcfe05fb9d1f5ba74f77f41928.

Reason for revert: breaking tot:

tast-remote-tests-cros-0.0.2-r9050: src/chromiumos/tast/local/bundles/cros/graphics/vt_switch.go:243:5: Errorf format %d has arg currtVTScreenshot of wrong type string


Original change's description:
> Refactor graphics.VTSwitch to use perceptualdiff
>
> Instead of counting pixels use the command line tool to determine if
> images are similar.
>
> BUG=b:208691958
> TEST=test run $IP graphics.VTSwitch.smoke
>
> Change-Id: I77edc40190888a3ce65d4a5c1dd33c2d12b7d309
> Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/tast-tests/+/3311192
> Reviewed-by: Po-Hsien Wang <pwang@chromium.org>
> Reviewed-by: Ilja Friedel <ihf@chromium.org>
> Tested-by: Ilja Friedel <ihf@chromium.org>
> Commit-Queue: Syed Faaiz Hussain <syedfaaiz@google.com>

Bug: b:208691958
Change-Id: Ieec94c724d00862aa81817bea6d5e08e5d3a987c