Update patch set 2
Patch Set 2:

Dry run: Failed builds:
  luci.chromeos.cq/cq-orchestrator JOB_FAILED https://cr-buildbucket.appspot.com/build/8839239721127691168
    Merge conflict detected! Please rebase and retry.
    
        error: patch failed: src/chromiumos/tast/remote/firmware/fingerprint/fingerprint.go:1
        Falling back to three-way merge...
        Applied patch to 'src/chromiumos/tast/remote/firmware/fingerprint/fingerprint.go' with conflicts.
        U src/chromiumos/tast/remote/firmware/fingerprint/fingerprint.go

Patch-set: 2
Tag: autogenerated:cv