Update patch set 2
Patch Set 2:

Failed builds:
  luci.chromeos.cq/cq-orchestrator JOB_FAILED https://cr-buildbucket.appspot.com/build/8870946453807984464
    Merge conflict detected! Please rebase and retry.
    
        error: patch failed: src/chromiumos/tast/local/crostini/pre.go:1
        Falling back to three-way merge...
        Applied patch to 'src/chromiumos/tast/local/crostini/pre.go' with conflicts.
        error: patch failed: src/chromiumos/tast/local/vm/container.go:1
        Falling back to three-way merge...
        Applied patch to 'src/chromiumos/tast/local/vm/container.go' cleanly.
        error: patch failed: src/chromiumos/tast/local/vm/images.go:1
        Falling back to three-way merge...
        Applied patch to 'src/chromiumos/tast/local/vm/images.go' cleanly.
        U src/chromiumos/tast/local/crostini/pre.go

Patch-set: 2
Tag: autogenerated:cq:full-run
Attention: {"person_ident":"Gerrit User 1309946 \u003c1309946@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"Someone else replied on the change"}