Update patch set 3
Patch Set 3:

Hi Meenakshi, if you're wondering why your CL isn't going through the CQ, it's because of this style-check issue:
```
tast-remote-tests-cros-0.0.1-r2964: src/chromiumos/tast/local/bundles/cros/arcappcompat/facebook.go:114:18: not enough arguments in call to act.Stop
```

Patch-set: 3
CC: Gerrit User 1386944 <1386944@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>