Revert "tast: Verify that correct Android is shipping"
This reverts commit 431644826e430350d0ae7c465dc427739a181c9a.

Reason for revert: Sheriff revert - This has been failing on many builders for some reason.
Example failure:
https://ci.chromium.org/p/chromeos/builders/postsubmit/sarien-snapshot/2253
Example log output:
tast-local-tests-cros-0.0.1-r1987: --- FAIL: TestSoftwareDeps (0.00s)
tast-local-tests-cros-0.0.1-r1987:     testcheck.go:70: arc.CheckAndroidVersion: missing software dependency "android|android_vm|android_vm_p|android_vm_r|android_both|android_p|android_r|android_all"
tast-local-tests-cros-0.0.1-r1987: FAIL


Original change's description:
> tast: Verify that correct Android is shipping
>
> This test ensures that we are not shipping 32-bit Android
> for 64-bit Kernels accidentally
>
> BUG=b:142830021
> TEST=tast run $IP arc.CheckAndroidVersion
>
> Change-Id: I6fe40ce62fb28b5aca8269c80f50bd6118ac360c
> Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/tast-tests/+/2040620
> Tested-by: Vaibhav Raheja <vraheja@chromium.org>
> Commit-Queue: Vaibhav Raheja <vraheja@chromium.org>
> Reviewed-by: Ereth McKnight-MacNeil <ereth@chromium.org>
> Reviewed-by: Eric Caruso <ejcaruso@chromium.org>

BUG=b:142830021

Exempt-From-Owner-Approval: causing widespread postsubmit builder failures
Change-Id: I49894c15d5d939714f68a1a15418de1ee532f943
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/tast-tests/+/2071855
Commit-Queue: Matthew Blecker <matthewb@chromium.org>
Tested-by: Matthew Blecker <matthewb@chromium.org>
Reviewed-by: Ereth McKnight-MacNeil <ereth@chromium.org>
Reviewed-by: Pavol Marko <pmarko@chromium.org>
Reviewed-by: Matthew Blecker <matthewb@chromium.org>