Update patch set 3
Patch Set 3:

This CL has failed the run. Reason:

Tryjob [chromeos/cq/cq-orchestrator](https://cr-buildbucket.appspot.com/build/8799957568464784513) has failed with summary:

---
Merge conflict detected! Please rebase and retry.

    Applied patch to 'chromeos-base/modemfwd-helpers-corsola/files/firmware_manifest.prototxt' with conflicts.
    error: chromeos-base/modemfwd-helpers-corsola/modemfwd-helpers-corsola-0.0.1-r4.ebuild: does not exist in index
    Applied patch to 'chromeos-base/modemfwd-helpers-guybrush/files/firmware_manifest.prototxt' cleanly.
    Falling back to direct application...
    Applied patch to 'chromeos-base/modemfwd-helpers-nissa/files/firmware_manifest.prototxt' cleanly.
    Falling back to direct application...
    Applied patch to 'chromeos-base/modemfwd-helpers-skyrim/files/firmware_manifest.prototxt' cleanly.
    Falling back to direct application...

Patch-set: 3
Attention: {"person_ident":"Gerrit User 1425417 \u003c1425417@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"ps#3: Tryjobs failed"}