Update patch set 8
Patch Set 8:

Failed builds:
  luci.chromeos.cq/cq-orchestrator JOB_FAILED https://cr-buildbucket.appspot.com/build/8857386997566600816
    Merge conflict detected! Please rebase and retry.
    
        error: patch failed: src/chromiumos/tast/local/chrome/chrome.go:1
        Falling back to three-way merge...
        Applied patch to 'src/chromiumos/tast/local/chrome/chrome.go' with conflicts.
        U src/chromiumos/tast/local/chrome/chrome.go

Patch-set: 8
Tag: autogenerated:cq:full-run