Update patch set 5
Patch Set 5:

Failed builds:
  luci.chromeos.cq/cq-orchestrator JOB_FAILED https://cr-buildbucket.appspot.com/build/8861180162377146368
    Merge conflict detected! Please rebase and retry.
    
        error: patch failed: src/chromiumos/tast/local/chrome/fixture.go:1
        Falling back to three-way merge...
        Applied patch to 'src/chromiumos/tast/local/chrome/fixture.go' with conflicts.
        U src/chromiumos/tast/local/chrome/fixture.go

Patch-set: 5
Tag: autogenerated:cq:full-run