Update patch set 4
Patch Set 4:

Dry run: Failed builds:
  luci.chromeos.cq/cq-orchestrator JOB_FAILED https://cr-buildbucket.appspot.com/build/8846575735922318528
    Merge conflict detected! Please rebase and retry.
    
        error: patch failed: src/chromiumos/tast/local/bundles/cros/arcappcompat/testutil/testutil.go:1
        Falling back to three-way merge...
        Applied patch to 'src/chromiumos/tast/local/bundles/cros/arcappcompat/testutil/testutil.go' with conflicts.
        U src/chromiumos/tast/local/bundles/cros/arcappcompat/testutil/testutil.go

Patch-set: 4
Tag: autogenerated:cq:dry-run