Update patch set 1
Patch Set 1:

A trybot failed to apply your change in https://cros-goldeneye.corp.google.com/chromeos/healthmonitoring/buildDetails?buildbucketId=8914713558686543072 . chromium:1588886 failed to apply due to a CQ issue: Unhandled exception occurred while applying changes: <class 'chromite.lib.cros_build_lib.RunCommandError'>: return code: 128; command: git fetch -f https://chromium-review.googlesource.com/chromiumos/platform/tast refs/changes/54/1589154/3
fatal: unable to access 'https://chromium-review.googlesource.com/chromiumos/platform/tast/': OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to chromium-review.googlesource.com:443 

cmd=['git', 'fetch', '-f', u'https://chromium-review.googlesource.com/chromiumos/platform/tast', u'refs/changes/54/1589154/3'], cwd=/b/s/w/ir/cache/cbuild/repository/src/platform/tast
Traceback (most recent call last):
  File "/b/s/w/ir/cache/cbuild/repository/chromite/lib/parallel.py", line 610, in TaskRunner
    task(*x, **task_kwargs)
  File "/b/s/w/ir/cache/cbuild/repository/chromite/lib/parallel.py", line 808, in <lambda>
    fn = lambda idx, task_args: out_queue.put((idx, task(*task_args)))
  File "/b/s/w/ir/cache/cbuild/repository/chromite/cbuildbot/patch_series.py", line 136, in _FetchChangesForRepo
    git.RunGit(repo, cmd, print_cmd=True)
  File "/b/s/w/ir/cache/cbuild/repository/chromite/lib/git.py", line 785, in RunGit
    return cros_build_lib.RunCommand(['git'] + cmd, **kwargs)
  File "/b/s/w/ir/cache/cbuild/repository/chromite/lib/cros_build_lib.py", line 658, in RunCommand
    raise RunCommandError(msg, cmd_result)
RunCommandError: return code: 128; command: git fetch -f https://chromium-review.googlesource.com/chromiumos/platform/tast refs/changes/54/1589154/3
fatal: unable to access 'https://chromium-review.googlesource.com/chromiumos/platform/tast/': OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to chromium-review.googlesource.com:443 

cmd=['git', 'fetch', '-f', u'https://chromium-review.googlesource.com/chromiumos/platform/tast', u'refs/changes/54/1589154/3'], cwd=/b/s/w/ir/cache/cbuild/repository/src/platform/tast


To be safe, we have kicked out all of the CLs, so that the commit queue does not go into an infinite loop retrying patches.

Commit queue documentation: https://dev.chromium.org/developers/tree-sheriffs/sheriff-details-chromium-os/commit-queue-overview

Patch-set: 1