Update patch set 11
Patch Set 11:

Failed builds:
  luci.chromeos.cq/cq-orchestrator JOB_FAILED https://cr-buildbucket.appspot.com/build/8878582875503738960
    Merge conflict detected! Please rebase and retry.
    
        error: patch failed: src/chromiumos/tast/local/bundles/cros/arc/window_manager_cuj.go:1
        Falling back to three-way merge...
        Applied patch to 'src/chromiumos/tast/local/bundles/cros/arc/window_manager_cuj.go' with conflicts.
        U src/chromiumos/tast/local/bundles/cros/arc/window_manager_cuj.go

Patch-set: 11
Tag: autogenerated:cq:full-run