Update patch set 1
Patch Set 1:

Dry run: Failed builds:
  luci.chromeos.cq/cq-orchestrator JOB_FAILED https://cr-buildbucket.appspot.com/build/8847395917349204976
    Merge conflict detected! Please rebase and retry.
    
        error: patch failed: test/suite_scheduler/configs/chromeos_engprod/app_compat.star:1
        Falling back to three-way merge...
        Applied patch to 'test/suite_scheduler/configs/chromeos_engprod/app_compat.star' with conflicts.
        error: patch failed: test/suite_scheduler/generated/suite_scheduler.cfg:1
        Falling back to three-way merge...
        Applied patch to 'test/suite_scheduler/generated/suite_scheduler.cfg' cleanly.
        error: patch failed: test/suite_scheduler/generated/suite_scheduler.ini:1
        Falling back to three-way merge...
        Applied patch to 'test/suite_scheduler/generated/suite_scheduler.ini' cleanly.
        U test/suite_scheduler/configs/chromeos_engprod/app_compat.star

Patch-set: 1
Tag: autogenerated:cq:dry-run