Update patch set 2
Patch Set 2:

Failed builds:
  luci.chromeos.cq/cq-orchestrator JOB_FAILED https://cr-buildbucket.appspot.com/build/8851137235193909984
    Merge conflict detected! Please rebase and retry.
    
        error: patch failed: src/chromiumos/tast/local/bundles/cros/wifi/hostap_hwsim.go:1
        Falling back to three-way merge...
        Applied patch to 'src/chromiumos/tast/local/bundles/cros/wifi/hostap_hwsim.go' with conflicts.
        U src/chromiumos/tast/local/bundles/cros/wifi/hostap_hwsim.go

Patch-set: 2
Tag: autogenerated:cq:full-run