Update patch set 10
Patch Set 10:

Failed builds:
  luci.chromeos.cq/cq-orchestrator JOB_FAILED https://cr-buildbucket.appspot.com/build/8830889902578708817
    Merge conflict detected! Please rebase and retry.
    
        error: src/chromiumos/tast/common/cros/crossdevice/attributes.go: does not exist in index
        error: cannot read the current contents of 'src/chromiumos/tast/common/cros/crossdevice/attributes.go'
        Falling back to direct application...
        Applied patch to 'src/chromiumos/tast/common/cros/nearbyshare/constants.go' cleanly.
        Falling back to direct application...
        Falling back to direct application...
        error: src/chromiumos/tast/common/cros/nearbyshare/nearbyutils.go: does not exist in index
        error: cannot read the current contents of 'src/chromiumos/tast/common/cros/nearbyshare/nearbyutils.go'
        Falling back to direct application...
        Applied patch to 'src/chromiumos/tast/local/bundles/cros/arc/nearby_share_send.go' cleanly.
        Applied patch to 'src/chromiumos/tast/local/bundles/cros/nearbyshare/cros_to_phone_high_vis.go' cleanly.
        Applied patch to 'src/chromiumos/tast/local/bundles/cros/nearbyshare/cros_to_phone_in_contacts.go' cleanly.
        Applied patch to 'src/chromiumos/tast/local/bundles/cros/nearbyshare/nearby_share_service.go' cleanly.
        Applied patch to 'src/chromiumos/tast/local/bundles/cros/nearbyshare/phone_to_cros_high_vis.go' cleanly.
        Applied patch to 'src/chromiumos/tast/local/bundles/cros/nearbyshare/phone_to_cros_in_contacts.go' cleanly.
        Applied patch to 'src/chromiumos/tast/local/bundles/cros/nearbyshare/phone_to_cros_not_visible.go' cleanly.
        Applied patch to 'src/chromiumos/tast/local/bundles/cros/nearbyshare/smoke_high_visibility_ui.go' cleanly.
        Applied patch to 'src/chromiumos/tast/local/bundles/cros/nearbyshare/smoke_snippet_library.go' cleanly.
        Applied patch to 'src/chromiumos/tast/local/chrome/crossdevice/android_setup.go' cleanly.
        Applied patch to 'src/chromiumos/tast/local/chrome/crossdevice/connected_android_device.go' cleanly.
        Applied patch to 'src/chromiumos/tast/local/chrome/crossdevice/cros_logging.go' cleanly.
        Applied patch to 'src/chromiumos/tast/local/chrome/crossdevice/fixture.go' cleanly.
        Applied patch to 'src/chromiumos/tast/local/chrome/nearbyshare/android_fixture.go' cleanly.
        Falling back to direct application...
        Applied patch to 'src/chromiumos/tast/local/chrome/nearbyshare/cros_setup.go' cleanly.
        Falling back to direct application...
        Applied patch to 'src/chromiumos/tast/local/chrome/nearbyshare/data/google_account_util.zip.external' with conflicts.
        Applied patch to 'src/chromiumos/tast/local/chrome/nearbyshare/fixture.go' cleanly.
        Applied patch to 'src/chromiumos/tast/local/chrome/nearbyshare/login_fixture.go' cleanly.
        Applied patch to 'src/chromiumos/tast/local/chrome/nearbyshare/nearbysnippet/constants.go' cleanly.
        Applied patch to 'src/chromiumos/tast/local/chrome/nearbyshare/nearbysnippet/snippet.go' cleanly.
        Applied patch to 'src/chromiumos/tast/local/chrome/nearbyshare/nearbytestutils/nearbytestutils.go' cleanly.
        Applied patch to 'src/chromiumos/tast/remote/bundles/cros/nearbyshare/cros_to_cros_high_vis.go' cleanly.
        Applied patch to 'src/chromiumos/tast/remote/bundles/cros/nearbyshare/cros_to_cros_in_contacts.go' cleanly.
        Applied patch to 'src/chromiumos/tast/remote/bundles/cros/nearbyshare/smoke_multi_dut_ui.go' cleanly.
        Applied patch to 'src/chromiumos/tast/remote/cros/nearbyshare/fixture.go' cleanly.
        U src/chromiumos/tast/local/chrome/nearbyshare/data/google_account_util.zip.external

Patch-set: 10
Tag: autogenerated:cq:full-run
Attention: {"person_ident":"Gerrit User 1118689 \u003c1118689@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"ps#10: CQ full run failed."}