Update patch set 2
Patch Set 2:

Failed builds:
  luci.chromeos.cq/cq-orchestrator JOB_FAILED https://cr-buildbucket.appspot.com/build/8803486862021909441
    Merge conflict detected! Please rebase and retry.
    
        Applied patch to 'src/chromiumos/tast/common/hwsec/cryptohome_binary.go' cleanly.
        Applied patch to 'src/chromiumos/tast/common/hwsec/cryptohome_client.go' cleanly.
        Applied patch to 'src/chromiumos/tast/local/bundles/cros/cryptohome/add_remove_factors.go' cleanly.
        Applied patch to 'src/chromiumos/tast/local/bundles/cros/cryptohome/add_remove_pin.go' cleanly.
        Applied patch to 'src/chromiumos/tast/local/bundles/cros/cryptohome/kiosk_ephemeral_mount.go' cleanly.
        Applied patch to 'src/chromiumos/tast/local/bundles/cros/cryptohome/kiosk_with_auth_factor_api.go' cleanly.
        Applied patch to 'src/chromiumos/tast/local/bundles/cros/cryptohome/kiosk_with_legacy_mount.go' cleanly.
        Applied patch to 'src/chromiumos/tast/local/bundles/cros/cryptohome/kiosk_with_prepare_credential_api.go' cleanly.
        Applied patch to 'src/chromiumos/tast/local/bundles/cros/cryptohome/kiosk_with_uss.go' cleanly.
        Applied patch to 'src/chromiumos/tast/local/bundles/cros/cryptohome/password_auth_factor_existing_vault_keyset.go' cleanly.
        Applied patch to 'src/chromiumos/tast/local/bundles/cros/cryptohome/recovery.go' cleanly.
        Applied patch to 'src/chromiumos/tast/local/bundles/cros/cryptohome/recovery_opt_out.go' cleanly.
        Applied patch to 'src/chromiumos/tast/local/bundles/cros/cryptohome/remove_credential_auth_session.go' cleanly.
        Applied patch to 'src/chromiumos/tast/local/bundles/cros/cryptohome/update_credential_auth_session.go' cleanly.
        Applied patch to 'src/chromiumos/tast/local/bundles/cros/cryptohome/update_password.go' cleanly.
        error: src/chromiumos/tast/local/bundles/cros/cryptohome/update_recovery.go: does not exist in index
        Applied patch to 'src/chromiumos/tast/local/bundles/cros/cryptohome/user_secret_stash.go' cleanly.
        Applied patch to 'src/chromiumos/tast/local/bundles/cros/cryptohome/user_secret_stash_add_pin.go' cleanly.
        Applied patch to 'src/chromiumos/tast/local/cryptohome/cryptohome.go' cleanly.
        Applied patch to 'src/chromiumos/tast/remote/bundles/cros/hwsec/check_key_perf.go' cleanly.
        Applied patch to 'src/chromiumos/tast/remote/bundles/cros/hwsec/pin_weaver_with_auth_api.go' cleanly.

Patch-set: 2
Tag: autogenerated:cq:full-run
Attention: {"person_ident":"Gerrit User 1126309 \u003c1126309@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"ps#2: CQ full run failed."}