Update patch set 1
Patch Set 1:

Failed builds:
  luci.chromeos.cq/cq-orchestrator JOB_FAILED https://cr-buildbucket.appspot.com/build/8873291156311811072
    Merge conflict detected! Please rebase and retry.
    
        error: patch failed: src/chromiumos/tast/common/shillconst/const.go:1
        Falling back to three-way merge...
        Applied patch to 'src/chromiumos/tast/common/shillconst/const.go' cleanly.
        error: patch failed: src/chromiumos/tast/local/bundles/cros/network/wifi_service.go:1
        Falling back to three-way merge...
        Applied patch to 'src/chromiumos/tast/local/bundles/cros/network/wifi_service.go' cleanly.
        error: patch failed: src/chromiumos/tast/services/cros/network/wifi_service.pb.go:1
        Falling back to three-way merge...
        Applied patch to 'src/chromiumos/tast/services/cros/network/wifi_service.pb.go' with conflicts.
        error: patch failed: src/chromiumos/tast/services/cros/network/wifi_service.proto:1
        Falling back to three-way merge...
        Applied patch to 'src/chromiumos/tast/services/cros/network/wifi_service.proto' cleanly.
        U src/chromiumos/tast/services/cros/network/wifi_service.pb.go

Patch-set: 1
Tag: autogenerated:cq:full-run
Attention: {"person_ident":"Gerrit User 1243287 \u003c1243287@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"reviewer or cc replied"}