Update patch set 7
Patch Set 7:

Failed builds:
  luci.chromeos.cq/cq-orchestrator JOB_FAILED https://cr-buildbucket.appspot.com/build/8880983669141187664
    Merge conflict detected! Please rebase and retry.
    
        error: patch failed: src/chromiumos/tast/remote/wificell/test_fixture.go:1
        Falling back to three-way merge...
        Applied patch to 'src/chromiumos/tast/remote/wificell/test_fixture.go' with conflicts.
        U src/chromiumos/tast/remote/wificell/test_fixture.go

Patch-set: 7
Tag: autogenerated:cq:full-run