Update patch set 1
Patch Set 1:

Dry run: Failed builds:
  luci.chromeos.cq/cq-orchestrator JOB_FAILED https://cr-buildbucket.appspot.com/build/8851821940579492864
    Merge conflict detected! Please rebase and retry.
    
        error: patch failed: src/chromiumos/tast/local/bundles/crosint/borealis/installer.go:1
        Falling back to three-way merge...
        Applied patch to 'src/chromiumos/tast/local/bundles/crosint/borealis/installer.go' with conflicts.
        U src/chromiumos/tast/local/bundles/crosint/borealis/installer.go

Patch-set: 1
Tag: autogenerated:cq:dry-run