Update patch set 6
Patch Set 6:

Failed builds:
  luci.chromeos.cq/cq-orchestrator JOB_FAILED https://cr-buildbucket.appspot.com/build/8844436672457549712
    Merge conflict detected! Please rebase and retry.
    
        error: patch failed: src/chromiumos/tast/remote/firmware/codelab/README.md:1
        Falling back to three-way merge...
        Applied patch to 'src/chromiumos/tast/remote/firmware/codelab/README.md' cleanly.
        error: patch failed: src/chromiumos/tast/remote/firmware/pre/pre.go:1
        Falling back to three-way merge...
        Applied patch to 'src/chromiumos/tast/remote/firmware/pre/pre.go' with conflicts.
        U src/chromiumos/tast/remote/firmware/pre/pre.go

Patch-set: 6
Tag: autogenerated:cq:full-run