Update patch set 2
Patch Set 2:

Failed builds:
  luci.chromeos.cq/cq-orchestrator JOB_FAILED https://cr-buildbucket.appspot.com/build/8850177303508248704
    Merge conflict detected! Please rebase and retry.
    
        error: patch failed: src/chromiumos/tast/remote/bundles/cros/typec/basic.go:1
        Falling back to three-way merge...
        Applied patch to 'src/chromiumos/tast/remote/bundles/cros/typec/basic.go' with conflicts.
        U src/chromiumos/tast/remote/bundles/cros/typec/basic.go

Patch-set: 2
Tag: autogenerated:cq:full-run