Update patch set 9
Patch Set 9:

Failed builds:
  luci.chromeos.cq/cq-orchestrator JOB_FAILED https://cr-buildbucket.appspot.com/build/8883988889657011136
    Merge conflict detected! Please rebase and retry.
    
        error: Failed to merge in the changes.
        hint: Use 'git am --show-current-patch' to see the failed patch
        CONFLICT (content): Merge conflict in src/chromiumos/tast/local/power/setup/setup_app.go
        CONFLICT (content): Merge conflict in src/chromiumos/tast/local/bundles/cros/arc/power_video_perf.go

Patch-set: 9
Tag: autogenerated:cq:full-run