Create patch set 7
Change has been successfully rebased and submitted as fe7b9ff18ee680e46d1a60ab69edf4a40c0ba02b

5 is the latest approved patch-set.
The change was submitted with unreviewed changes in the following files:

```
The name of the file: src/chromiumos/tast/local/bundles/cros/apps/cross_origin_forbidden.go
Insertions: 7, Deletions: 6.

@@ -27,10 +27,12 @@
 	"chromiumos/tast/testing"
 )
 
-const mainAppFile = "cross_origin_forbidden_index.html"
-const serverKeyFile = "cross_origin_forbidden_key.pem"
-const serverCertificateFile = "cross_origin_forbidden_certificate.pem"
-const certificateAuthorityFile = "cross_origin_forbidden_ca_cert.pem"
+const (
+	mainAppFile              = "cross_origin_forbidden_index.html"
+	serverKeyFile            = "cross_origin_forbidden_key.pem"
+	serverCertificateFile    = "cross_origin_forbidden_certificate.pem"
+	certificateAuthorityFile = "cross_origin_forbidden_ca_cert.pem"
+)
 
 func init() {
 	testing.AddTest(&testing.Test{
@@ -58,7 +60,6 @@
 }
 
 func CrossOriginForbidden(ctx context.Context, s *testing.State) {
-
 	cr := s.FixtValue().(chrome.HasChrome).Chrome()
 	fdms := s.FixtValue().(fakedms.HasFakeDMS).FakeDMS()
 
@@ -97,7 +98,7 @@
 	if server.Error != nil {
 		s.Fatal("Could not start https server: ", err)
 	}
-	defer server.Server.Close()
+	defer server.Close()
 
 	policies := []policy.Policy{
 		&policy.WebAppInstallForceList{
```
```
The name of the file: src/chromiumos/tast/local/bundles/cros/apps/isolatedapp/https.go
Insertions: 11, Deletions: 5.

@@ -59,7 +59,7 @@
 */
 type HTTPSServer struct {
 	ServerConfiguration HTTPSServerConfiguration
-	Server              *http.Server
+	server              *http.Server
 	Address             string
 	Error               error
 	handler             httpsHandler
@@ -68,10 +68,16 @@
 var server HTTPSServer
 
 /*
+Close shuts down a server that was started with the StartServer function.
+*/
+func (server HTTPSServer) Close() error {
+	return server.server.Close()
+}
+
+/*
 StartServer starts up an https server without blocking.
 Returns a Server instance containing
 - the server configuration,
-- the http server control object,
 - the base address,
 - an error object in case the server could not be started.
 */
@@ -79,7 +85,7 @@
 
 	server = HTTPSServer{
 		ServerConfiguration: configuration,
-		Server:              &http.Server{},
+		server:              &http.Server{},
 		Address:             "",
 		Error:               nil,
 		handler:             httpsHandler{},
@@ -94,8 +100,8 @@
 		server.Error = err
 		return server
 	}
-	server.Server.Handler = &server.handler
-	go server.Server.ServeTLS(listener, configuration.ServerCertificatePath, configuration.ServerKeyPath)
+	server.server.Handler = &server.handler
+	go server.server.ServeTLS(listener, configuration.ServerCertificatePath, configuration.ServerKeyPath)
 	server.Address = fmt.Sprintf("https://localhost:%d", listener.Addr().(*net.TCPAddr).Port)
 	return server
 
```


Patch-set: 7
Patch-set-description: Rebase
Subject: tast-test for isolated app cross origin behavior.
Status: merged
Commit: fe7b9ff18ee680e46d1a60ab69edf4a40c0ba02b
Tag: autogenerated:gerrit:merged
Groups: 57e53f065db9bd592a58a83cb13d0f2b9bcd759e
Label: Code-Review=+2, 0d2699d7e3c9a4394e0eda6cd3f324778ff8d0bd Gerrit User 1368736 <1368736@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Label: Commit-Queue=+2, c6ed3b15787e72d5a5a03afc45b0b3b0f5ae1244 Gerrit User 1526977 <1526977@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Label: Verified=+1, ccd5e4bb2f14f2f0578116e50eb935d876111b65 Gerrit User 1526977 <1526977@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Label: SUBM=+1, 456ada735d5e2381d5950859bacb323e342a9fff
Submission-id: 3429239
Submitted-with: OK
Submitted-with: Rule-Name: gerrit~PrologRule
Submitted-with: MAY: Auto-Submit
Submitted-with: MAY: Owners-Override
Submitted-with: MAY: Bot-Commit
Submitted-with: OK: Verified: Gerrit User 1526977 <1526977@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Submitted-with: MAY: Commit-Queue
Submitted-with: OK: Code-Review: Gerrit User 1368736 <1368736@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Submitted-with: OK
Submitted-with: Rule-Name: Code-Owners