Update patch set 1
Patch Set 1:

Failed builds:
  luci.chromeos.cq/cq-orchestrator JOB_FAILED https://cr-buildbucket.appspot.com/build/8878474366224628640
    Merge conflict detected! Please rebase and retry.
    
        error: patch failed: src/chromiumos/tast/local/bundles/cros/ui/hotseat_scroll_perf.go:1
        Falling back to three-way merge...
        Applied patch to 'src/chromiumos/tast/local/bundles/cros/ui/hotseat_scroll_perf.go' with conflicts.
        U src/chromiumos/tast/local/bundles/cros/ui/hotseat_scroll_perf.go

Patch-set: 1
Tag: autogenerated:cq:full-run