Update patch set 4
Patch Set 4:

Failed builds:
  luci.chromeos.cq/cq-orchestrator JOB_FAILED https://cr-buildbucket.appspot.com/build/8877824728356627936
    Merge conflict detected! Please rebase and retry.
    
        error: patch failed: src/chromiumos/tast/services/cros/network/wifi_service.pb.go:1
        Falling back to three-way merge...
        Applied patch to 'src/chromiumos/tast/services/cros/network/wifi_service.pb.go' with conflicts.
        error: patch failed: src/chromiumos/tast/services/cros/network/wifi_service.proto:1
        Falling back to three-way merge...
        Applied patch to 'src/chromiumos/tast/services/cros/network/wifi_service.proto' cleanly.
        U src/chromiumos/tast/services/cros/network/wifi_service.pb.go

Patch-set: 4
Tag: autogenerated:cq:full-run