Update patch set 1
Patch Set 1:

Dry run: Failed builds:
  luci.chromeos.cq/cq-orchestrator JOB_FAILED https://cr-buildbucket.appspot.com/build/8862795194620643104
    Merge conflict detected! Please rebase and retry.
    
        error: patch failed: src/chromiumos/tast/local/bundles/cros/camera/hal3_device.go:1
        Falling back to three-way merge...
        Applied patch to 'src/chromiumos/tast/local/bundles/cros/camera/hal3_device.go' with conflicts.
        error: patch failed: src/chromiumos/tast/local/bundles/cros/camera/hal3_module.go:1
        Falling back to three-way merge...
        Applied patch to 'src/chromiumos/tast/local/bundles/cros/camera/hal3_module.go' with conflicts.
        U src/chromiumos/tast/local/bundles/cros/camera/hal3_device.go
        U src/chromiumos/tast/local/bundles/cros/camera/hal3_module.go

Patch-set: 1
Tag: autogenerated:cq:dry-run